version: '3'
services:
  openliberty:
    build: ../../images/openliberty
    environment:
      - PORT=1234
      - DATABASE_URL=postgres://root:123456@database:5432/root
      - GAMIFY_SERVER=$GAMIFY_SERVER
      - GAMIFY_API_TOKEN=$GAMIFY_API_TOKEN
    ports:
      - "8080:1234"

networks:
  default:
    external:
      name: stack-net
